[leaderboard]
url = "/games/leaderboard"

[privacy]
  [[privacy.intervals]]
  lower = 0
  upper = 33
  message = """
  HoulÃ , attention Ã  la protection de vos donnÃ©es ! Vous semblez enclin Ã  les partager davantage que des chewing-gum dans une cours de rÃ©crÃ©ation. Câ€™est difficile Ã  rÃ©cupÃ©rer par la suiteâ€¦
  """
  [[privacy.intervals]]
  lower = 33
  upper = 67
  message = """
  Vous Ãªtes en bonne voie, mais vous pouvez mieux faire. Enfin, peut-Ãªtre que vous nâ€™avez pas spÃ©cialement de temps pour penser Ã  tout.
  """

  [[privacy.intervals]]
  lower = 67
  upper = 100
  message = """
  Bravo ! Vous avez rÃ©ussi Ã  trouver comment limiter la quantitÃ© dâ€™informations divulguÃ©es, ou de conditions Ã  accepter.
  """

[time]
  [[time.intervals]]
  lower = 0
  upper = 33
  message = """
  Visiblement, vous aimez prendre votre temps pour surfer sur le web en toute sÃ©rÃ©nitÃ©. Mais aurez-vous toujours autant de temps Ã  votre disposition ?
  """
  [[time.intervals]]
  lower = 33
  upper = 67
  message = """
  Rapide, mais pas trop ! Vous prenez le temps dâ€™analyser lâ€™essentiel. Un bon compromis entre temps et libertÃ© dâ€™agirâ€¦ enfin, câ€™est Ã  vous de voir.
  """

  [[time.intervals]]
  lower = 67
  upper = 100
  message = """
  Vous nâ€™avez pas de temps Ã  perdre ! Prenez quand mÃªme le temps dâ€™analyser quelques Ã©lÃ©ments de navigation, ne serait-ce que lâ€™essentiel.
  """



[[games]]
name="start"
url = "/games/site_start"
congrat = "Tada ğŸµ, premier piÃ¨ge et vous venez d'etre Ã©valuÃ© ! Voici votre score initial"
message = """
Vous lâ€™aurez compris, votre objectif sur cette application est de progresser sur un simulateur de site internet, en essayant de trouver le parfait compromis entre votre temps et votre intÃ©gritÃ©. Vous allez donc rÃ©aliser quelques petits dÃ©fis afin de mettre votre bon sens en pratique.

Etes-vous prÃªt(e) ? Câ€™est parti !
"""

[[games]]
name="ifff"
url = "/games/challenge-article-ifff"

[end]
name="end"
content="""
<h1>You have to click "end"</h1>
<form action="/">
    <input type="submit" value="end" />
</form>
"""
